wireguard: fix missing ipv6_dst_lookup
fixes:

```
kernel/oneplus/sm8150/net/wireguard/socket.c:139:20: error: no member named 'ipv6_dst_lookup' in 'struct ipv6_stub'                                                                                                                                                  
                dst = ipv6_stub->ipv6_dst_lookup_flow(sock_net(sock), sock, &fl,                                                                                                                                                                                                                                               
                      ~~~~~~~~~  ^                                                                                                                                                                                                                                                                                             
kernel/oneplus/sm8150/net/wireguard/compat/compat.h:90:42: note: expanded from macro 'ipv6_dst_lookup_flow'                                                                                                                                                          
#define ipv6_dst_lookup_flow(a, b, c, d) ipv6_dst_lookup(a, b, &dst, c) + (void *)0 ?: dst
```